spring:
  application:
    name: rsfit-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rsfit}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${SPRING_AI_VERTEX_PROJECT_ID:rsfit-app}
          location: ${SPRING_AI_VERTEX_LOCATION:us-central1}
          api-key: ${SPRING_AI_VERTEX_AI_GEMINI_API_KEY:}
          model: gemini-pro
server:
  port: 8080
